version: '2'
services:
  nodeserver:
    build:
      context: ../development/server/
    environment:
      - DATABASE_ADDR=mongo
      - OSS_ADDR=ossserver
    links:
      - mongo
      - ossserver
    depends_on:
      - mongo
      - ossserver
    volumes:
      - datavolume:/usr/src/app/uploads
    restart: always
  mongo:
    image: mongo
    restart: always
  nginx:
    build:
     context: nginx/
    links:
      - nodeserver
    volumes:
      - datavolume:/usr/share/nginx/files
    restart: always
  ossserver:
    build:
     context: .
     dockerfile: oss/Dockerfile
    restart: always
    volumes:
      - datavolume:/files
volumes:
  datavolume: {}
