version: '2'
services:
  nodeserver:
    build:
      context: ../development/server/
    environment:
      - DATABASE_ADDR=mongo
      - OSS_ADDR=ossserver
    links:
      - mongo
      - ossserver
    depends_on:
      - mongo
      - ossserver
  mongo:
    image: mongo
  nginx:
    build:
     context: nginx/
    links:
      - nodeserver
  ossserver:
    image: ossserver
