version: '2'
services:
  node:
    volumes:
      - ../development/server/coverage:/usr/src/app/coverage/
    command: node node_modules/.bin/istanbul cover -x '**/*.spec.js' node_modules/.bin/_mocha server.spec.js
