version: '2'
services:
  nodeserver:
    volumes:
      - ../development/server/coverage:/usr/src/app/coverage/
    command: node node_modules/.bin/istanbul cover node_modules/.bin/_mocha server.spec.js
