---
- name: Stop all running containers
  become: yes
  shell: for container_id in $(docker ps -a -q);do docker stop $container_id;done

- name: Run mongodb container
  become: yes
  shell: docker run --restart=always -p 27017:27017 -d mongo  

  # use single task, because ansible cannot pass through commandline parameters
- name: Run nginx container
  become: yes
  shell: docker run --restart=always -v /vagrant/development:/usr/share/nginx/html:ro -d -p 8080:80 nginx

- name: Build OSS container
  become: yes
  shell: docker build -t ossserver -f /vagrant/provision/roles/staging/files/oss/Dockerfile .

- name: Run default OSS container
  become: yes
  #shell: docker run -d -p 9090:9090 ossserver
  shell: docker run -d -v /vagrant/provision/roles/staging/volume:/srv -p 9090:9090 ossserver

- name: Build Nodeserver container
  become: yes
  shell: docker build -t nodeserver -f /vagrant/provision/roles/staging/files/node/Dockerfile .

- name: Run Nodeserver container
  become: yes
  shell: docker run --restart=always -d -p 8888:8888 -v /vagrant/development/server:/usr/src/app nodeserver
# this container does not work atm: the node html reporter is broken
#- name: Build Nodetest container
#  become: yes
#  shell: docker build -t continuoustest -f /vagrant/provision/roles/staging/files/continuoustest/Dockerfile .

#- name: Run Nodetest container
#  become: yes
#  shell: docker run --restart=always -d -v /vagrant/development/server:/usr/src/app continuoustest