version: '2'
services:
  nodeserver:
    build:
      context: .
    ports:
    - "8888:3000"
    environment:
    - DATABASE_ADDR=mongo
    links:
    - mongo
    - ossserver
  mongo:
    image: mongo
  nginx:
    image: nginx
    ports:
    - "8887:80"
  ossserver:
    image: ossserver
