version: '2'
services:
  nodeserver:
    build:
      context: .
    environment:
    - DATABASE_ADDR=mongo
    links:
    - mongo
    - ossserver
  mongo:
    image: mongo
  nginx:
    image: nginx
  ossserver:
    image: ossserver
